export const CUSTOMERS = [
  {
    id: 1,
    name: 'Arjun Mehta',
    phone: '9550105897',
    avatar: 'AM',
    service: 'Premium Haircut + Beard Styling',
    serviceCode: 'PHB',
    bookingType: 'Walk-in',
    status: 'In Chair',
    arrivalTime: '10:15 AM',
    duration: '45 min',
    barber: 'Ravi S.',
    notes: 'Prefers scissor cut only. No clippers on top. Sensitive scalp — use gentle shampoo.',
    loyaltyPts: 340,
    visits: 18,
  },
  {
    id: 2,
    name: 'Vikram Nair',
    phone: '9735897907',
    avatar: 'VN',
    service: 'Classic Shave',
    serviceCode: 'CS',
    bookingType: 'Appointment',
    status: 'Waiting',
    arrivalTime: '10:30 AM',
    duration: '30 min',
    barber: 'Suresh P.',
    notes: '',
    loyaltyPts: 120,
    visits: 6,
  },
  {
    id: 3,
    name: 'Rohan Desai',
    phone: '9812345670',
    avatar: 'RD',
    service: 'Hair Colour + Cut',
    serviceCode: 'HCC',
    bookingType: 'Appointment',
    status: 'Completed',
    arrivalTime: '09:00 AM',
    duration: '90 min',
    barber: 'Ravi S.',
    notes: 'Regular customer. Likes light brown tones. Check last colour formula.',
    loyaltyPts: 580,
    visits: 31,
  },
  {
    id: 4,
    name: 'Sahil Joshi',
    phone: '9876543210',
    avatar: 'SJ',
    service: 'Beard Trim',
    serviceCode: 'BT',
    bookingType: 'Walk-in',
    status: 'Waiting',
    arrivalTime: '10:45 AM',
    duration: '20 min',
    barber: 'Unassigned',
    notes: 'First time visit.',
    loyaltyPts: 0,
    visits: 1,
  },
]

export const STATUS_META = {
  'In Chair':  {
    bg: 'bg-accent/15', border: 'border-accent/50',
    text: 'text-accent', dot: 'bg-accent',
    label: 'In Chair',
  },
  'Waiting': {
    bg: 'bg-amber-100', border: 'border-amber-400/60',
    text: 'text-amber-700', dot: 'bg-amber-500',
    label: 'Waiting',
  },
  'Completed': {
    bg: 'bg-emerald-50', border: 'border-emerald-400/60',
    text: 'text-emerald-700', dot: 'bg-emerald-500',
    label: 'Completed',
  },
}

export const SERVICES = [
  'Classic Haircut',
  'Premium Haircut + Beard Styling',
  'Classic Shave',
  'Beard Trim',
  'Hair Colour + Cut',
  'Scalp Treatment',
  'Kids Haircut',
  'Head Massage',
]

export const BOOKING_TYPES = ['Walk-in', 'Appointment', 'Online']
