export const TICKET_STATUS = {
  OPEN: 'Open',
  IN_PROGRESS: 'In Progress',
  RESOLVED: 'Resolved',
  ESCALATED: 'Escalated',
  CLOSED: 'Closed',
}

export const TICKET_PRIORITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical',
}

export const TICKET_TYPE = {
  CUSTOMER: 'Customer Issue',
  SALON: 'Salon Issue',
}

export const mockTickets = [
  {
    id: 'TKT-1001',
    title: 'Unable to complete online booking',
    description: 'Customer is unable to complete online booking. The payment gateway throws an error at checkout after entering card details.',
    type: TICKET_TYPE.CUSTOMER,
    status: TICKET_STATUS.OPEN,
    priority: TICKET_PRIORITY.HIGH,
    customer: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    phone: '+91 98765 43210',
    assignee: 'Graphura',
    createdAt: '2026-05-15T09:30:00',
    updatedAt: '2026-05-15T11:00:00',
    tags: ['payment', 'booking'],
    notes: [
      { author: 'Graphura', text: 'Investigating the payment gateway logs.', timestamp: '2026-05-15T11:00:00' },
    ],
  },
  {
    id: 'TKT-1002',
    title: 'Salon staff login issue',
    description: 'The salon manager at Glamour Studio cannot log into the admin panel. Password reset is not sending emails.',
    type: TICKET_TYPE.SALON,
    status: TICKET_STATUS.IN_PROGRESS,
    priority: TICKET_PRIORITY.CRITICAL,
    customer: 'Glamour Studio',
    email: 'manager@glamourstudio.in',
    phone: '+91 87654 32109',
    assignee: 'Graphura',
    createdAt: '2026-05-14T14:20:00',
    updatedAt: '2026-05-15T08:45:00',
    tags: ['login', 'authentication', 'email'],
    notes: [
      { author: 'Graphura', text: 'Email SMTP config checked — issue found with domain whitelist.', timestamp: '2026-05-15T08:45:00' },
    ],
  },
  {
    id: 'TKT-1003',
    title: 'Wrong stylist assigned to appointment',
    description: 'Customer was assigned a different stylist than the one they chose during booking. Requests refund or reschedule.',
    type: TICKET_TYPE.CUSTOMER,
    status: TICKET_STATUS.ESCALATED,
    priority: TICKET_PRIORITY.HIGH,
    customer: 'Ananya Mehta',
    email: 'ananya.m@gmail.com',
    phone: '+91 76543 21098',
    assignee: 'Graphura',
    createdAt: '2026-05-13T10:00:00',
    updatedAt: '2026-05-14T16:30:00',
    tags: ['appointment', 'stylist', 'refund'],
    notes: [
      { author: 'Graphura', text: 'Escalated to billing team for refund approval.', timestamp: '2026-05-14T16:30:00' },
    ],
  },
  {
    id: 'TKT-1004',
    title: 'Salon profile photos not uploading',
    description: 'The salon is unable to upload new portfolio photos. The upload interface shows a 413 error after selecting images.',
    type: TICKET_TYPE.SALON,
    status: TICKET_STATUS.RESOLVED,
    priority: TICKET_PRIORITY.MEDIUM,
    customer: 'Silk & Scissors',
    email: 'info@silkscissors.in',
    phone: '+91 65432 10987',
    assignee: 'Graphura',
    createdAt: '2026-05-12T09:15:00',
    updatedAt: '2026-05-13T12:00:00',
    tags: ['upload', 'media', 'profile'],
    notes: [
      { author: 'Graphura', text: 'Increased server upload limit from 2MB to 10MB. Issue resolved.', timestamp: '2026-05-13T12:00:00' },
    ],
  },
  {
    id: 'TKT-1005',
    title: 'App crashes after selecting service',
    description: 'Multiple customers report the mobile app crashes immediately after selecting a service from the menu.',
    type: TICKET_TYPE.CUSTOMER,
    status: TICKET_STATUS.OPEN,
    priority: TICKET_PRIORITY.CRITICAL,
    customer: 'Multiple Users',
    email: 'support@platform.in',
    phone: '-',
    assignee: 'Unassigned',
    createdAt: '2026-05-15T07:00:00',
    updatedAt: '2026-05-15T07:00:00',
    tags: ['mobile', 'crash', 'app'],
    notes: [],
  },
  {
    id: 'TKT-1006',
    title: 'Incorrect earnings shown in salon dashboard',
    description: 'The salon dashboard shows incorrect monthly earnings. The figure is significantly lower than actual bookings completed.',
    type: TICKET_TYPE.SALON,
    status: TICKET_STATUS.IN_PROGRESS,
    priority: TICKET_PRIORITY.HIGH,
    customer: 'Bliss Beauty Lounge',
    email: 'accounts@blisslounge.in',
    phone: '+91 54321 09876',
    assignee: 'Graphura',
    createdAt: '2026-05-11T13:45:00',
    updatedAt: '2026-05-14T10:20:00',
    tags: ['billing', 'earnings', 'dashboard'],
    notes: [
      { author: 'Graphura', text: 'Found discrepancy in payout calculation logic for cancelled and rescheduled bookings.', timestamp: '2026-05-14T10:20:00' },
    ],
  },
  {
    id: 'TKT-1007',
    title: 'Customer did not receive confirmation email',
    description: 'Customer booked an appointment but did not receive any confirmation email or SMS. Appointment exists in the system.',
    type: TICKET_TYPE.CUSTOMER,
    status: TICKET_STATUS.CLOSED,
    priority: TICKET_PRIORITY.LOW,
    customer: 'Rohan Desai',
    email: 'rohan.d@yahoo.com',
    phone: '+91 43210 98765',
    assignee: 'Graphura',
    createdAt: '2026-05-10T16:00:00',
    updatedAt: '2026-05-11T09:30:00',
    tags: ['email', 'notification', 'confirmation'],
    notes: [
      { author: 'Graphura', text: 'Resent confirmation manually. Notified dev team about email queue delay.', timestamp: '2026-05-11T09:30:00' },
    ],
  },
  {
    id: 'TKT-1008',
    title: 'Salon requesting feature: bulk schedule management',
    description: 'Salon owner requests a bulk schedule update feature for public holidays and special events.',
    type: TICKET_TYPE.SALON,
    status: TICKET_STATUS.ESCALATED,
    priority: TICKET_PRIORITY.LOW,
    customer: 'Radiance Salon & Spa',
    email: 'owner@radiancespa.in',
    phone: '+91 32109 87654',
    assignee: 'Graphura',
    createdAt: '2026-05-09T11:30:00',
    updatedAt: '2026-05-12T15:00:00',
    tags: ['feature-request', 'schedule', 'salon'],
    notes: [
      { author: 'Graphura', text: 'Escalated to product team for roadmap consideration.', timestamp: '2026-05-12T15:00:00' },
    ],
  },
]

export const mockAgents = ['Graphura', 'Unassigned']

export const getStats = (tickets) => {
  return {
    total: tickets.length,
    open: tickets.filter(t => t.status === TICKET_STATUS.OPEN).length,
    inProgress: tickets.filter(t => t.status === TICKET_STATUS.IN_PROGRESS).length,
    escalated: tickets.filter(t => t.status === TICKET_STATUS.ESCALATED).length,
    resolved: tickets.filter(t => t.status === TICKET_STATUS.RESOLVED).length,
    closed: tickets.filter(t => t.status === TICKET_STATUS.CLOSED).length,
    customerIssues: tickets.filter(t => t.type === TICKET_TYPE.CUSTOMER).length,
    salonIssues: tickets.filter(t => t.type === TICKET_TYPE.SALON).length,
    critical: tickets.filter(t => t.priority === TICKET_PRIORITY.CRITICAL).length,
  }
}
